//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int ID_Check { get; set; }
        public int ID_Order { get; set; }
        public System.DateTime DateCheck { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
