//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Check = new HashSet<Check>();
            this.ListOrder = new HashSet<ListOrder>();
        }
    
        public int ID_Order { get; set; }
        public int ID_Table { get; set; }
        public int ID_User { get; set; }
        public int ID_WayPay { get; set; }
        public int ID_Status { get; set; }
        public System.DateTime DateOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check> Check { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListOrder> ListOrder { get; set; }
        public virtual StatusOrder StatusOrder { get; set; }
        public virtual Tables Tables { get; set; }
        public virtual Users Users { get; set; }
        public virtual WayPay WayPay { get; set; }
    }
}
