//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShift
    {
        public int ID_WorkShift { get; set; }
        public System.DateTime DateShift { get; set; }
        public int ID_User { get; set; }
        public Nullable<int> ID_Table { get; set; }
    
        public virtual Tables Tables { get; set; }
        public virtual Users Users { get; set; }
    }
}
